inherit_gem:
  unasukecop:
    - "config/rubocop.yml"

Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Style/PercentLiteralDelimiters:
  Enabled: false
