AllCops:
  TargetRubyVersion: 2.3

inherit_gem:
  unasukecop:
    - "config/rubocop.yml"

Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: percent_r

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'mikoshi.gemspec'

Metrics/CyclomaticComplexity:
  Max: 8
